[2:11 AM, 4/3/2026] Bilal Mughal: import streamlit as st
import pandas as pd
import folium
from streamlit_folium import st_folium
from PIL import Image
import openai
from fpdf import FPDF
import urllib.parse
import os

# --- 1. CONFIG & SYSTEM ---
st.set_page_config(page_title="Babar Real Estate | CEO Bilal Mughal", layout="wide")
openai.api_key = st.secrets.get("OPENAI_API_KEY", "")

# --- 2. PREMIUM CSS ---
st.markdown("""
<style>
    .stApp { background-color: #f4f7f6; }
    .main-header { background: #003366; color: white; padding: 25px; text-align: center; border-radius: 0 0 20px 20px; }
    .footer-wa { background-color: #25D366; color: white; padding: 12px; text-align: center; position: fixed; bottom: 0; width: 100%; font-weight: bold; z-index: 1000; }
    .bill-box { border: 2px dash…
[2:13 AM, 4/3/2026] Bilal Mughal: import streamlit as st
import pandas as pd
import folium
from streamlit_folium import st_folium
from PIL import Image
import openai
from fpdf import FPDF
import urllib.parse
import os

# --- 1. SETTINGS & THEME ---
st.set_page_config(page_title="Babar Real Estate | CEO Bilal Mughal", layout="wide")

st.markdown("""
<style>
    .stApp { background-color: #f8f9fa; }
    .header-box { background: #003366; color: white; padding: 25px; text-align: center; border-radius: 0 0 25px 25px; margin-bottom: 20px; }
    .footer-wa { background: #25D366; color: white; padding: 12px; text-align: center; position: fixed; bottom: 0; width: 100%; font-weight: bold; z-index: 999; }
    .stat-card { background: white; padding: 20px; border-radius: 15px; box-shadow: 0 4px 12px rgba(0,0,0,0.05); text-align: center; border-top: 5px solid #C5A059; }
</style>
""", unsafe_allow_html=True)

# --- 2. ASSETS & BRANDING ---
# Logo aur CEO image handle karne ke liye
col_a, col_b = st.columns([4, 1])
with col_a:
    if os.path.exists("assets/logo.png"):
        st.image("assets/logo.png", width=200)
    else:
        st.title("BABAR REAL ESTATE")
with col_b:
    if os.path.exists("assets/ceo.png"):
        st.image("assets/ceo.png", width=80)

st.markdown("<div class='header-box'><h1>BABAR REAL ESTATE</h1><p>Broadway Plaza C-116, Phase 8, DHA Lahore</p></div>", unsafe_allow_html=True)

# --- 3. DATA ENGINE ---
@st.cache_data
def load_babar_data():
    if os.path.exists("data/dha_sample.csv"):
        return pd.read_csv("data/dha_sample.csv")
    else:
        # Emergency Data agar file missing ho
        return pd.DataFrame({
            'Phase': ['Phase 8', 'Phase 9 Prism'], 'Block': ['Broadway', 'Sector A'],
            'PlotSize': ['1 Kanal', '1 Kanal'], 'Price': [75000000, 33500000],
            'Latitude': [31.4697, 31.4450], 'Longitude': [74.4534, 74.4800]
        })

df = load_babar_data()

# --- 4. TABS NAVIGATION ---
tab1, tab2, tab3, tab4, tab5 = st.tabs(["📊 Dashboard", "📍 Maps", "🤖 AI Advisor", "🧮 Calculator", "⚙️ Admin"])

# Dashboard Section
with tab1:
    st.subheader("Market Overview 🚀")
    m1, m2 = st.columns(2)
    m1.metric("Total Listings", "1,240", "↑ 12 Today")
    m2.metric("ROI Potential", "18.5%", "High")
    st.markdown("### Featured Properties")
    st.dataframe(df, use_container_width=True)

# Maps Section
with tab2:
    st.subheader("🗺️ Interactive DHA Map")
    m = folium.Map(location=[31.4697, 74.4534], zoom_start=12)
    for _, row in df.iterrows():
        folium.Marker([row['Latitude'], row['Longitude']], 
                      popup=f"{row['Phase']} - PKR {row['Price']:,}").add_to(m)
    st_folium(m, width="100%", height=450)

# AI Advisor Section
with tab3:
    st.subheader("🤖 AI Investment Advisor")
    user_q = st.text_input("Investement ke bare mein poochein:")
    if user_q:
        st.info(f"Bilal Mughal's AI Insight: '{user_q}' ke liye Phase 9 Prism sector A aur C behtareen hain.")

# Calculator Section (Bill Generator)
with tab4:
    st.subheader("🧮 Construction Bill Generator")
    p_size = st.selectbox("Plot Size", ["5 Marla", "10 Marla", "1 Kanal"])
    p_rate = st.number_input("Rate per Marla (PKR)", value=1200000)
    
    sqft_val = {"5 Marla": 1950, "10 Marla": 3300, "1 Kanal": 5500}
    total_est = (sqft_val[p_size] / 225) * p_rate

    st.markdown(f"""
        <div style='border:2px dashed #003366; padding:20px; background:white; text-align:center;'>
            <h3>PKR {total_est:,.0f}</h3>
            <p>{p_size} Estimate Generated by Bilal Mughal</p>
        </div>
    """, unsafe_allow_html=True)

    # PDF Logic
    pdf = FPDF()
    pdf.add_page()
    pdf.set_font("Arial", 'B', 16)
    pdf.cell(0, 10, "Babar Real Estate - Official Bill", ln=True, align='C')
    pdf.set_font("Arial", '', 12)
    pdf.cell(0, 10, f"Plot Size: {p_size} | Total: PKR {total_est:,.0f}", ln=True)
    
    st.download_button("📥 Download PDF Bill", 
                       data=pdf.output(dest='S').encode('latin-1'), 
                       file_name=f"Babar_Bill_{p_size}.pdf")

# Admin Section
with tab5:
    if st.text_input("Admin Password", type="password") == "babar123":
        st.success("Welcome, CEO Bilal Mughal")
        st.file_uploader("Upload New DHA Data (CSV)")
    else:
        st.warning("Password required.")

# --- 5. FOOTER ---
st.markdown("<div class='footer-wa'><a href='https://wa.me/923244000041' style='color:white; text-decoration:none;'>WhatsApp: Babar Mughal (+92 324 4000041)</a></div>", unsafe_allow_html=True)
